### ISSUE TITLE
Compiler warnings with recent gcc

### ISSUE THREAD

**Issue by flmei** [mgelde/CWrap#1]
Hi!
The checkcall.hpp shows a lot of compiler warnings if you compile it with a recent gcc version.
```
checkcall.hpp:182:13: warning: mangled name for 'auto cppc::callChecked(Callable&&, Args&& ...) [with R = cppc::IsNotNullptrReturnCheckPolicy; E = OpenSSLExceptionErrorPolicy; Callable = evp_pkey_ctx_st* (&)(evp_pkey_st*, engine_st*) noexcept; Args = {evp_pkey_st*&, std::nullptr_t}]' will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
 inline auto callChecked(Callable&& callable, Args&&... args) {
```

Plx fix :D

**Comment by mgelde** [comment]
How recent is "recent"? Do you maybe see this gcc bug [1]?

With GCC 8.2.1 I cannot reproduce this. I've tried with std=c++14 and std=c++17. In the first case, my gcc will not even detect the `noexcept` (as expected) and in the latter case it will simply compile without issue.

Tested with:
GCC 8.2.1
`-Wall -Wextra -Wnoexcept-type`

Please reopen with more info* an a mwe.

*More info is:
- compiler version
- precise compiler flags needed to reproduce
- minimal working example

[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=77369

**Comment by flmei** [comment]
Recent was not so recent, it's gcc 7.3.0 ;)
Thanks for pointing this out!
